version: '3.3'

services:
  load_balancer:
    image: nginx
    ports:
      - "8383:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    build: .
    command: >
      bash -c "
      uvicorn app.main:app --log-level info --use-colors --interface asgi3 --timeout-keep-alive 50 --reload --workers 1000 --host 0.0.0.0 --port 8001"
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8001"
